/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#012d1d',
        'on-primary': '#ffffff',
        'primary-container': '#1b4332',
        'on-primary-container': '#86af99',
        'primary-fixed': '#c1ecd4',
        'primary-fixed-dim': '#a5d0b9',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#274e3d',
        'inverse-primary': '#a5d0b9',
        secondary: '#2b694d',
        'on-secondary': '#ffffff',
        'secondary-container': '#b0f1cc',
        'on-secondary-container': '#327053',
        'secondary-fixed': '#b0f1cc',
        'secondary-fixed-dim': '#94d4b1',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#0c5136',
        tertiary: '#152b1c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#2a4131',
        'on-tertiary-container': '#93ad98',
        'tertiary-fixed': '#cee9d3',
        'tertiary-fixed-dim': '#b3cdb7',
        'on-tertiary-fixed': '#092012',
        'on-tertiary-fixed-variant': '#354c3b',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f7fafb',
        'on-background': '#181c1d',
        surface: '#f7fafb',
        'surface-dim': '#d7dadb',
        'surface-bright': '#f7fafb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f5',
        'surface-container': '#ebeeef',
        'surface-container-high': '#e6e9ea',
        'surface-container-highest': '#e0e3e4',
        'surface-variant': '#e0e3e4',
        'surface-tint': '#3f6653',
        'on-surface': '#181c1d',
        'on-surface-variant': '#414844',
        'inverse-surface': '#2d3132',
        'inverse-on-surface': '#eef1f2',
        outline: '#717973',
        'outline-variant': '#c1c8c2',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        base: '8px',
        gutter: '24px',
        'container-max': '1200px',
      },
      fontFamily: {
        serif: ['"Noto Serif"', 'Georgia', 'serif'],
        sans: ['Manrope', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['36px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        h3: ['28px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      maxWidth: {
        container: '1200px',
      },
      boxShadow: {
        card: '0 16px 24px rgba(1,45,29,0.06)',
        'card-hover': '0 24px 40px rgba(1,45,29,0.12)',
        modal: '0 32px 64px -12px rgba(1,45,29,0.25)',
        nav: '0 1px 3px rgba(1,45,29,0.08)',
      },
    },
  },
  plugins: [],
};
